# Generated by Django 4.1.7 on 2023-03-12 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_first_name', models.CharField(max_length=100)),
                ('fan_last_name', models.CharField(max_length=100)),
                ('fan_nationality', models.CharField(max_length=100)),
                ('fan_date_of_birth', models.DateField()),
                ('fa_email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Swimmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swimmer_last_name', models.CharField(max_length=100)),
                ('swimmer_first_name', models.CharField(max_length=100)),
                ('swimmer_county', models.CharField(max_length=100)),
                ('swimmer_date_of_birth', models.DateField()),
                ('swimmer_years_of_experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_founding_year', models.IntegerField()),
                ('team_budget', models.IntegerField()),
                ('team_motto', models.CharField(max_length=100)),
                ('team_abbreviation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SwimmerFan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_page_name', models.CharField(max_length=100)),
                ('fan_since_year', models.CharField(max_length=5)),
                ('fan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.fan')),
                ('swimmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.swimmer')),
            ],
        ),
        migrations.AddField(
            model_name='swimmer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.team'),
        ),
        migrations.AddField(
            model_name='fan',
            name='swimmers',
            field=models.ManyToManyField(through='app1.SwimmerFan', to='app1.swimmer'),
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_first_name', models.CharField(max_length=100)),
                ('coach_last_name', models.CharField(max_length=100)),
                ('coach_years_of_experience', models.IntegerField()),
                ('coach_date_of_birth', models.DateField()),
                ('coach_email', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.team', unique=True)),
            ],
        ),
    ]
