# Generated by Django 4.1.7 on 2023-03-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fan',
            old_name='fa_email',
            new_name='fan_email',
        ),
    ]
