# Generated by Django 4.1.7 on 2023-03-13 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_swimmerfan_fan_since_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swimmers', to='app1.team'),
        ),
    ]
