# Generated by Django 4.1.7 on 2023-03-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_alter_swimmer_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="swimmer",
            name="fans",
            field=models.ManyToManyField(through="app1.SwimmerFan", to="app1.fan"),
        ),
    ]
