# Generated by Django 4.1.7 on 2023-05-03 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_swimmer_fans"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coach",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="fan",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="swimmer",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="swimmerfan",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="team",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="team",
            name="team_description",
            field=models.CharField(default="", max_length=5000),
        ),
        migrations.AlterField(
            model_name="coach",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.team"
            ),
        ),
        migrations.AddIndex(
            model_name="coach",
            index=models.Index(fields=["team"], name="app1_coach_team_id_e62863_idx"),
        ),
        migrations.AddIndex(
            model_name="fan",
            index=models.Index(
                fields=["fan_first_name", "fan_last_name", "fan_email"],
                name="app1_fan_fan_fir_a92e92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fan",
            index=models.Index(
                fields=["fan_first_name"], name="app1_fan_fan_fir_41266e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="swimmer",
            index=models.Index(
                fields=["team", "id"], name="app1_swimme_team_id_b8de09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="swimmer",
            index=models.Index(
                fields=["swimmer_years_of_experience", "id"],
                name="app1_swimme_swimmer_6c2654_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="swimmer",
            index=models.Index(
                fields=["swimmer_first_name"], name="app1_swimme_swimmer_371d62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="swimmerfan",
            index=models.Index(
                fields=["swimmer", "fan"], name="app1_swimme_swimmer_46c0ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="swimmerfan",
            index=models.Index(
                fields=["swimmer"], name="app1_swimme_swimmer_74c294_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="swimmerfan",
            index=models.Index(fields=["fan"], name="app1_swimme_fan_id_1e1eeb_idx"),
        ),
        migrations.AddIndex(
            model_name="swimmerfan",
            index=models.Index(
                fields=["fan_page_name"], name="app1_swimme_fan_pag_5c133a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="swimmerfan",
            index=models.Index(
                fields=["fan_since_year"], name="app1_swimme_fan_sin_29a501_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["team_name"], name="app1_team_team_na_c7b24d_idx"
            ),
        ),
    ]
