# Generated by Django 4.1.7 on 2023-05-03 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app1", "0006_alter_coach_options_alter_fan_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_first_name", models.CharField(max_length=100)),
                ("user_last_name", models.CharField(max_length=100)),
                ("user_date_of_birth", models.DateField()),
                ("user_bio", models.CharField(max_length=1000)),
                ("user_location", models.CharField(max_length=100)),
                ("activation_code", models.CharField(max_length=36)),
                ("activation_expiry_date", models.DateTimeField()),
                ("active", models.BooleanField()),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
        ),
    ]
