# Generated by Django 4.1.7 on 2023-03-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_fa_email_fan_fan_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swimmerfan',
            name='fan_since_year',
            field=models.IntegerField(),
        ),
    ]
